# Generated by Django 4.2.6 on 2024-05-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_marca_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='id',
            new_name='idMarca',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='idProducto',
        ),
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
